############################################
# Netlify Build Configuration
# Password Reset Frontend
############################################

[build]
  command = "npm run build"
  publish = "build"
  base = "."  # root folder (where package.json is)

# Set environment variables for consistent builds
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"                # prevents CRA from treating warnings as errors
  TAILWIND_MODE = "build"     # ensures tailwind builds properly
  REACT_APP_ENV = "production"

############################################
# Redirects — support React Router (SPA)
############################################
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

############################################
# Optional: Cache npm dependencies between builds
############################################
[build.cache]
  paths = ["node_modules", "build"]

############################################
# (Optional) Headers — enable gzip & caching
############################################
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
